DROP TABLE IF EXISTS tourneys;
DROP TABLE IF EXISTS player_choices;

DROP SEQUENCE IF EXISTS sq_tourneyid;
DROP SEQUENCE IF EXISTS sq_choiceid;

CREATE SEQUENCE sq_tourneyid;
CREATE SEQUENCE sq_choiceid;

CREATE TABLE tourneys
(
  tourney_id       INTEGER GENERATED BY DEFAULT AS IDENTITY SEQUENCE sq_tourneyid PRIMARY KEY,
  name            VARCHAR2(200) NOT NULL,
  is_active       BOOLEAN,
  start_date      TIMESTAMP,
  finish_date     TIMESTAMP
);

CREATE TABLE player_choices
(
  choice_id          INTEGER GENERATED BY DEFAULT AS IDENTITY SEQUENCE sq_choiceid PRIMARY KEY,
  tourney_id         INTEGER NOT NULL,
  member_id          INTEGER NOT NULL,
  participation     BOOLEAN NOT NULL,
  action_date       TIMESTAMP NOT NULL,
  FOREIGN KEY (tourney_id) REFERENCES tourneys(tourney_id),
  CONSTRAINT  unique_by_tourney_and_member UNIQUE(tourney_id, member_id),
);



